# 开发环境配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:endfield}?currentSchema=public
    username: ${DB_USERNAME:endfield}
    password: ${DB_PASSWORD:endfield}

  # Liquibase 日志
  liquibase:
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    com.adrainty.stock: DEBUG
    liquibase: INFO
